region: ap-southeast-2
role: arn:aws:iam::794381291637:role/service-role/dataChallengeAdmin
policy: arn:aws:iam::794381291637:policy/service-role/AWSLambdaBasicExecutionRole-b22f742a-85f9-4042-b0fe-8782efa5671c
