service: list-sec-groups

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-2
  endpointType: REGIONAL
  role: arn:aws:iam::794381291637:role/service-role/dataChallengeAdmin
  iamManagedPolicies: # Optional IAM Managed Policies, which allows to include the policies into IAM Role
    - arn:aws:iam::794381291637:policy/service-role/AWSLambdaBasicExecutionRole-b22f742a-85f9-4042-b0fe-8782efa5671c

functions:
  app:
    handler: app.handler # reference the file and exported method
    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger
          path: app
          method: get
          cors: false
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: false
